<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.sqlite2j</groupId>
    <artifactId>sqlite2j-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <artifactId>sqlite2j-vm</artifactId>
  <name>sqlite2j-vm</name>
  <dependencies>
    <dependency>
      <groupId>org.sqlite2j</groupId>
      <artifactId>sqlite2j-compiler</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.sqlite2j</groupId>
      <artifactId>sqlite2j-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
